FitnessPlanet/Controllers/ClientController.cs
using FitnessPlanet.Domain;
using FitnessPlanet.Models.Client;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp;
using System.Linq;
using System.Threading.Tasks;

namespace FitnessPlanet.Controllers
{
    public class ClientController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;

        public ClientController(UserManager<ApplicationUser> userManager)
        {
            this.userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            var allUsers = this.userManager.Users.Select(u => new ClientIndexVM
            {
                Id = u.Id,
                UserName = u.UserName,
                FirstName = u.FirstName,
                LastName = u.LastName,
                Address = u.Address,
                PhoneNumber = u.PhoneNum,
                Email = u.Email
            }).ToList();

            var adminIds = (await this.userManager.GetUsersInRoleAsync("Administrator")).Select(a => a.Id).ToList();

            foreach (var user in allUsers)
            {
                user.IsAdmin = adminIds.Contains(user.Id);
            }

            var users = allUsers.Where(x => x.IsAdmin == false).OrderBy(x => x.UserName).ToList();
            return this.View(users);
        }
        public ActionResult Delete(string id)
        {
            var user = this.userManager.Users.FirstOrDefault(x => x.Id == id);

            if (user == null)
                return NotFound();


            ClientDeleteVM userToDelete = new ClientDeleteVM()
            {
                Id = user.Id,
                FirstName = user.FirstName,
                LastName = user.LastName,
                Address = user.Address,
                Email = user.Email,
                PhoneNumber = user.PhoneNum,
                UserName = user.UserName
            };
            return View(userToDelete);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(ClientDeleteVM bindingModel)
        {
            string id = bindingModel.Id;
            var user = await userManager.FindByIdAsync(id);
            if (user == null)
                return NotFound();

            else
            {
                IdentityResult result = await userManager.DeleteAsync(user);
                if (result.Succeeded)
                    return RedirectToAction("SuccessDeleteUser");
                else
                    return NotFound();
            }
        }
        public ActionResult SuccessDeleteUser()
        {
            return View();
        }
    }
}

FitnessPlanet/Controllers/ContactsController.cs
using FitnessPlanet.Data;
using FitnessPlanet.Domain;
using FitnessPlanet.Models.Contact;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using System.Threading.Tasks;

namespace FitnessPlanet.Controllers
{
    public class ContactsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ContactsController(ApplicationDbContext context)
        {
            _context = context;
        }

        [HttpPost]
        public async Task<IActionResult> AddMessage(ContactFormVM form)
        {
            if (ModelState.IsValid)
            {
                var message = new ContactMessage
                {
                    Id = form.Id,
                    FirstName = form.FirstName,
                    LastName = form.LastName,
                    Email = form.Email,
                    Message = form.Message,
                    CreatedAt = DateTime.Now
                };

                _context.ContactMessages.Add(message);
                await _context.SaveChangesAsync();

                TempData["Message"] = "Your message has been sent successfully.";

                return RedirectToAction("ContactForm");
            }

            return View(form);
        }
        [Authorize(Roles = "Administrator")]
        public IActionResult Index()
        {
            var messages = _context.ContactMessages.ToList();
            return View(messages);
        }
        [HttpGet]
        public IActionResult ContactForm()
        {
            var contactForm = new ContactFormVM();
            return View(contactForm);
        }
    }
}

FitnessPlanet/Controllers/OrderController.cs
using FitnessPlanet.Data;
using FitnessPlanet.Domain;
using FitnessPlanet.Models.Order;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.Linq;
using System.Security.Claims;

namespace FitnessPlanet.Controllers
{
    public class OrderController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrderController(ApplicationDbContext context)
        {
            this._context = context;
        }
        [Authorize(Roles = "Administrator")]
        public IActionResult Index()
        {
            string userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = _context.Users.SingleOrDefault(u=> u.Id == userId);

            List<OrderIndexVM> orders = _context.Orders.Select(x => new OrderIndexVM
            {
                Id = x.Id,
                OrderDate = x.OrderDate.ToString("dd-MMM,yyyy hh:mm", CultureInfo.InvariantCulture),
                UserId = x.UserId,
                User = x.User.UserName,
                ProductId = x.ProductId,
                Product = x.Product.ProductName,
                Picture = x.Product.Picture,
                Color = x.Product.Color,
                Quantity = x.Quantity,
                Price = x.Price,
                Discount = x.Discount,
                TotalPrice = x.TotalPrice,
                Description = x.Description
            }).ToList();
            return View(orders);
        }

        public IActionResult MyOrders(string searchString)
        {
            string currentUserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = this._context.Users.SingleOrDefault(u => u.Id == currentUserId);

            if (user == null)
                return null;

            List<OrderIndexVM> orders = _context.Orders.Where(x => x.UserId == user.Id).Select(x => new OrderIndexVM
            {
                Id = x.Id,
                OrderDate = x.OrderDate.ToString("dd-MMM,yyyy hh:mm", CultureInfo.InvariantCulture),
                UserId = x.UserId,
                User = x.User.UserName,
                ProductId = x.ProductId,
                Product = x.Product.ProductName,
                Picture = x.Product.Picture,
                Color = x.Product.Color,
                Quantity = x.Quantity,
                Price = x.Price,
                Discount = x.Discount,
                TotalPrice = x.TotalPrice,
                Description = x.Description
            }).ToList();

            if (!String.IsNullOrEmpty(searchString))
                orders = orders.Where(o => o.Product.ToLower().Contains(searchString.ToLower())).ToList();

            return this.View(orders);
        }

        public ActionResult Create(int productId, int quantity)
        {
            string userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = this._context.Users.SingleOrDefault(u => u.Id == userId);
            var product = this._context.Products.SingleOrDefault(x => x.Id == productId);

            if (user == null || product == null || quantity < 1 || quantity > product.Quantity)
            {
                TempData["ErrorMessage"] = $"The quantity should be between 1 and {product.Quantity}.";

                return RedirectToAction("Index", "Product");
            }

            OrderConfirmVM orderForDb = new OrderConfirmVM
            {
                UserId = userId,
                User = user.UserName,
                ProductId = productId,
                ProductName = product.ProductName,
                Picture = product.Picture,
                Color = product.Color,

                Quantity = quantity,
                Price = product.Price,
                Discount = product.Discount,
                TotalPrice = quantity * product.Price - quantity * product.Price * product.Discount / 100,
                Description = product.Description
            };
            return View(orderForDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(OrderConfirmVM bindingModel)
        {
                if (this.ModelState.IsValid)
                {
                    string userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                    var user = this._context.Users.SingleOrDefault(u => u.Id == userId);
                    var product = this._context.Products.SingleOrDefault(x => x.Id == bindingModel.ProductId);

                    if (user == null || product == null || product.Quantity < bindingModel.Quantity || bindingModel.Quantity == 0)
                    { return this.RedirectToAction("Index", "Product"); }

                    Order orderForDb = new Order
                    {
                        OrderDate = DateTime.UtcNow,
                        ProductId = bindingModel.ProductId,
                        UserId = userId,
                        Quantity = bindingModel.Quantity,
                        Price = product.Price,
                        Discount = product.Discount,
                        Description = product.Description,
                        Color = product.Color
                    };

                    product.Quantity -= bindingModel.Quantity;
                    this._context.Products.Update(product);
                    this._context.Orders.Add(orderForDb);
                    this._context.SaveChanges();
                }
                return this.RedirectToAction("Index", "Product");
        }
    }
}

FitnessPlanet/Controllers/StatisticsController.cs
using FitnessPlanet.Abstraction;
using FitnessPlanet.Models.Statistics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FitnessPlanet.Controllers
{
    [Authorize(Roles ="Administrator")]
    public class StatisticsController : Controller
    {
        private readonly IStatisticsService statisticsService;
        public StatisticsController(IStatisticsService statisticsService)
        {
            this.statisticsService = statisticsService;
        }
        public IActionResult Index()
        {
            StatisticsVM statistics = new StatisticsVM();

            statistics.CountClients = statisticsService.CountClients();
            statistics.CountProducts = statisticsService.CountProducts();
            statistics.CountOrders = statisticsService.CountOrders();
            statistics.SumOrders = statisticsService.SumOrders();

            return View(statistics);
        }
    }
}

FitnessPlanet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FitnessPlanet</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-pink border-bottom border-dark rounded mb-3" style="background-color: #e86363;">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="font-weight: bold; font-family: 'Montserrat', sans-serif; font-size: 24px;">FitnessPlanet</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-black" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-black" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-black" asp-area="" asp-controller="Product" asp-action="">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-black" asp-area="" asp-controller="Contacts" asp-action="ContactForm">Contacts</a>
                        </li>
                        @if (this.User.Identity.IsAuthenticated)
                        {

                            <li class="nav-item">
                                <a class="nav-link text-black" asp-area="" asp-controller="Order" asp-action="MyOrders">My Orders</a>
                            </li>
                        }
                        @if ((this.User.Identity.IsAuthenticated) && (this.User.IsInRole("Administrator")))
                        {
                            <li class="nav-item active">
                                <div class="dropdown show">
                                    <a class="nav-link active dropdown-toggle text-black" href="#" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="background-color: #e86363;">
                                        Statistic Module
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                        <a class="dropdown-item" asp-controller="Client" asp-action="Index"><i class="fas fa-user"></i> Clients</a>
                                        <a class="dropdown-item" asp-controller="Order" asp-action="Index"><i class="fas fa-shopping-cart"></i> Orders</a>
                                        <a class="dropdown-item" asp-controller="Statistics" asp-action="Index"><i class="fas fa-pencil-square-o"></i> Statistics</a>
                                        <a class="dropdown-item" asp-controller="Contacts" asp-action="Index"><i class="fas fa-envelope"></i> Messages</a>
                                    </div>
                                </div>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top border-black footer text-muted" style="background-color: #de6262; padding: 20px 0;">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-md-4">
                    <a href="https://www.facebook.com/" class="social-icon"><i class="fab fa-facebook fa-lg"></i></a>
                    <a href="https://www.instagram.com/" class="social-icon"><i class="fab fa-instagram fa-lg"></i></a>
                    <a href="https://twitter.com" class="social-icon"><i class="fab fa-twitter fa-lg"></i></a>
                </div>
                <div class="col-sm-6 col-md-4">
                    <p style="color: black; font-weight: bold;">&copy; 2023 - FitnessPlanet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></p>
                </div>
                <div class="col-sm-12 col-md-4">
                    <ul class="list-inline text-md-right">
                        <p style="color: black; font-weight: bold;"><a asp-area="" asp-controller="Contacts" asp-action="ContactForm"><i class="fas fa-envelope"></i> Contact Us</a></p>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>